# Generated by Django 3.2.5 on 2021-08-31 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doctor', models.CharField(max_length=200, verbose_name='Имя доктора')),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ethnicity', models.CharField(max_length=50, verbose_name='Наименование ethnicity')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_patient', models.CharField(max_length=200, verbose_name='ФИО')),
                ('day_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('ethnicity_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.ethnicity')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_visit', models.CharField(max_length=20, verbose_name='Номер визита')),
                ('date', models.DateField()),
                ('age_visit', models.IntegerField()),
                ('inform_consent', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No')),
                ('comply_all_study', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No')),
                ('female_age', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No')),
                ('current_preg_lact', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No')),
                ('history_hysterectomy', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No')),
                ('risk_no_compliance', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No')),
                ('unwillingness', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No')),
                ('medicince_listed_now_10', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No')),
                ('medicince_listed_3month_10', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No')),
                ('PCOS', models.IntegerField(blank=True, null=True)),
                ('Exclusion', models.IntegerField(blank=True, null=True)),
                ('Grey', models.IntegerField(blank=True, null=True)),
                ('Phenotype', models.CharField(blank=True, max_length=1, verbose_name='Фенотип')),
                ('PCOS_text', models.TextField(blank=True, max_length=500, verbose_name='Заключение')),
                ('Exclusion_text', models.TextField(blank=True, max_length=500, verbose_name='ПричиныИсключения')),
                ('doctor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.doctor')),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ultrasound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_ovary_key', models.IntegerField()),
                ('right_ovary_key', models.IntegerField()),
                ('date', models.DateField()),
                ('right_ovary_volume', models.FloatField()),
                ('right_ovary_follicle', models.FloatField()),
                ('diameter_cyst_right', models.FloatField()),
                ('left_ovary_volume', models.FloatField()),
                ('left_ovary_follicle', models.FloatField()),
                ('diameter_cyst_left', models.FloatField()),
                ('left_ovary_front', models.FloatField()),
                ('right_ovary_front', models.FloatField()),
                ('left_ovary_posterior', models.FloatField()),
                ('right_ovary_posterior', models.FloatField()),
                ('left_ovary_side', models.FloatField()),
                ('right_ovary_side', models.FloatField()),
                ('doctor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.doctor')),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('visit_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value_testosteron', models.FloatField()),
                ('value_shbg', models.FloatField()),
                ('value_dheas', models.FloatField()),
                ('value_tsh', models.FloatField()),
                ('day_mens_prl', models.IntegerField()),
                ('value_17hp', models.FloatField()),
                ('value_prl', models.FloatField()),
                ('value_testosteron_unit_key', models.IntegerField()),
                ('value_shbg_unit_key', models.IntegerField()),
                ('value_dheas_unit_key', models.IntegerField()),
                ('value_tsh_unit_key', models.IntegerField()),
                ('value_17hp_unit_key', models.IntegerField()),
                ('value_prl_unit_key', models.IntegerField()),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('visit_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('periods', models.IntegerField()),
                ('type_menstual_disorders_1', models.IntegerField()),
                ('type_menstual_disorders_2', models.IntegerField()),
                ('type_menstual_disorders_3', models.IntegerField()),
                ('type_menstual_disorders_4', models.IntegerField()),
                ('min_menstrual', models.IntegerField()),
                ('max_menstrual', models.IntegerField()),
                ('sum_physician', models.IntegerField()),
                ('doctor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.doctor')),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('visit_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
    ]
